version: 2.1

orbs:
    node: circleci/node@1.1.6
    artifactory: circleci/artifactory@1.0.0

jobs:
  build_and_test:
    executor: 
        name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - artifactory/docker-publish:
            docker-registry: yokota-circle-artifactory.jfrog.io
            docker-tag: 'yokota-circle-artifactory.jfrog.io/jfrog-circle-demo:1.0-${CIRCLE_BUILD_NUM}'
            name: Docker Publish 
            repository: docker-local
            requires:
                - build_and_test
            filters:
                branches:
                    only: master