version: 2.1

orbs:
    node: circleci/node@1.1.6
    artifactory: circleci/artifactory@1.0.0

jobs:
  xray_cli:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - setup_remote_docker
      #this can be automated with this orb i believe: https://circleci.com/orbs/registry/orb/circleci/artifactory
      - artifactory/install
      - artifactory/configure:
          artifactory-key: ARTIFACTORY_API_KEY
          artifactory-url: ARTIFACTORY_URL
          artifactory-user: ARTIFACTORY_USER
      - run: 
          name: Build Docker image
          command: |
            docker build -t $ARTIFACTORY_DOCKER_REGISTRY/circle-artifactory:$CIRCLE_BUILD_NUM .
      - run:
          name: Log in to Docker
            docker login --username=$ARTIFACTORY_USER --password-stdin=$ARTIFACTORY_API_KEY $ARTIFACTORY_DOCKER_REGISTRY
      - run:
          name: Docker build and push (and other commands)
          command: 
            docker push yokota-circle-artifactory.jfrog.io/circle-artifactory:$CIRCLE_BUILD_NUM
            jfrog rt dp yokota-circle-artifactory.jfrog.io/circle-artifactory:$CIRCLE_BUILD_NUM circle-artifactory --build-name=circle-artifactory --build-number=$CIRCLE_BUILD_NUM
            jfrog rt bp circle-artifactory $CIRCLE_BUILD_NUM
            jfrog rt bs circle-artifactory $CIRCLE_BUILD_NUM
            
workflows:
  build_test_deploy:
    jobs:
      #this job gets my Dockerfile to JFrog
      # - artifactory/docker-publish:
      #     docker-registry: $ARTIFACTORY_DOCKER_REGISTRY
      #     docker-tag: '$ARTIFACTORY_DOCKER_REGISTRY/circle-artifactory:${CIRCLE_BUILD_NUM}'
      #     name: Build and tag Docker image & push to JFrog Docker Registry 
      #     repository: circle-artifactory
      #     filters:
      #         branches:
      #             only: master
      #this job invokes the job above. want to know best way to use the API.
      - xray_cli