version: 2.1

orbs:
  node: circleci/node@2.0.3
  artifactory: circleci/artifactory@1.0.0

jobs:
  build-scan-promote:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - setup_remote_docker
      - artifactory/install
      - artifactory/configure:
          artifactory-key: ARTIFACTORY_API_KEY
          artifactory-url: ARTIFACTORY_URL
          artifactory-user: ARTIFACTORY_USER
      - run: 
          name: Build Docker image
          command: |
            docker build -t $ARTIFACTORY_DOCKER_REGISTRY/circle-artifactory:$CIRCLE_BUILD_NUM .
      - run:
          name: Log in to Docker
          command: |
            docker login --username=$ARTIFACTORY_USER --password=$ARTIFACTORY_API_KEY $ARTIFACTORY_DOCKER_REGISTRY
      - run: 
          name: JFrog Commands 
          command: |
            jfrog rt dp yokota-circle-artifactory.jfrog.io/circle-artifactory:$CIRCLE_BUILD_NUM circle-artifactory --build-name=circle-artifactory --build-number=$CIRCLE_BUILD_NUM
            jfrog rt bp circle-artifactory $CIRCLE_BUILD_NUM
            jfrog rt bs circle-artifactory $CIRCLE_BUILD_NUM
  promote:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - artifactory/install
      - artifactory/configure:
          artifactory-key: ARTIFACTORY_API_KEY
          artifactory-url: ARTIFACTORY_URL
          artifactory-user: ARTIFACTORY_USER
      - run:
          name: Promote
          command: jfrog rt bpr circle-artifactory $CIRCLE_BUILD_NUM docker-local
            
workflows:
  build_test_deploy:
    jobs:
      - node/test:
          name: node-tests
      - build-scan:
          requires:
            - node-tests
      - hold:
          type: approval
          requires:
            - build-scan
          filters:
            branches:
              only: master
      - promote:
          requires:
            - hold