version: 2.1

orbs:
    node: circleci/node@1.1.6
    artifactory: circleci/artifactory@1.0.0

jobs:
  xray_cli:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      #this can be automated with this orb i believe: https://circleci.com/orbs/registry/orb/circleci/artifactory
      - run:
          name: Install jFrog CLI
          command: 
            sudo npm i -g npm
            sudo npm install jfrog-cli-go
      - run: jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY --interactive=false
      - run: |
          jfrog rt bs jfrog-circle-demo 1.0-${CIRCLE_BUILD_NUM}
          echo "curl command will go here"
        
workflows:
  build_test_deploy:
    jobs:
      #this job gets my Dockerfile to JFrog
      - artifactory/docker-publish:
          docker-registry: yokota-circle-artifactory.jfrog.io
          docker-tag: 'yokota-circle-artifactory.jfrog.io/jfrog-circle-demo:1.0-${CIRCLE_BUILD_NUM}'
          name: jfrog_docker_publish 
          repository: circle-artifactory
          filters:
              branches:
                  only: master
      #this job invokes the job above. want to know best way to use the API.
      - xray_cli:
          requires:
            - jfrog_docker_publish