version: 2.1

orbs:
    node: circleci/node@1.1.6
    artifactory: circleci/artifactory@1.0.0

jobs:
  xray_cli:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY --interactive=false
      - run: curl -X POST docker://yokota-circle-artifactory.jfrog.io/jfrog-circle-demo:1.0-${CIRCLE_BUILD_NUM}
        
workflows:
  build_test_deploy:
    jobs:
      - artifactory/docker-publish:
          docker-registry: yokota-circle-artifactory.jfrog.io
          docker-tag: 'yokota-circle-artifactory.jfrog.io/jfrog-circle-demo:1.0-${CIRCLE_BUILD_NUM}'
          name: Docker Publish 
          repository: circle-artifactory
          filters:
              branches:
                  only: master
      - xray_cli:
          requires:
            - Docker Publish