version: 2.1

orbs:
    node: circleci/node@1.1.6

jobs:
  build_and_test:
    executor: 
        name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy: 
    executor: node_executor
    steps:
      - checkout

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master