version: 2.1

orbs:
    node: circleci/node@1.1.6
    artifactory: circleci/artifactory@1.0.0

jobs:
  xray_cli:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - setup_remote_docker
      #this can be automated with this orb i believe: https://circleci.com/orbs/registry/orb/circleci/artifactory
      - artifactory/install
      - artifactory/configure:
          artifactory-key: ARTIFACTORY_API_KEY
          artifactory-url: ARTIFACTORY_URL
          artifactory-user: ARTIFACTORY_USER
      - run: 
          command: |
            docker pull hello-world
            docker tag hello-world:latest yokota-circle-artifactory.jfrog.io/hello-world:latest
            docker push yokota-circle-artifactory.jfrog.io/hello-world:latest
            jfrog rt dp yokota-circle-artifactory.jfrog.io/hello-world:latest circle-artifactory --build-name=circle-artifactory --build-number=$CIRCLE_BUILD_NUM
            jfrog rt bp circle-artifactory $CIRCLE_BUILD_NUM
            jfrog rt bs circle-artifactory $CIRCLE_BUILD_NUM
            
workflows:
  build_test_deploy:
    jobs:
      #this job gets my Dockerfile to JFrog
      # - artifactory/docker-publish:
      #     docker-registry: yokota-circle-artifactory.jfrog.io
      #     docker-tag: 'yokota-circle-artifactory.jfrog.io/jfrog-circle-demo:1.0-${CIRCLE_BUILD_NUM}'
      #     name: jfrog_docker_publish 
      #     repository: circle-artifactory
      #     filters:
      #         branches:
      #             only: master
      #this job invokes the job above. want to know best way to use the API.
      - xray_cli